name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Select Xcode Version
      run: sudo xcode-select -s /Applications/Xcode_12.2.app
    - name: Build
      run: |
        pod install --repo-update --clean-install
        xcodebuild test -workspace Giphy.xcworkspace -scheme Giphy -destination 'platform=iOS Simulator,name=iPhone 12 Pro,OS=14.2'
    - name: Run tests
      run: swift test -v
